### ISSUE TITLE
Dominios inativos

### ISSUE THREAD

**Issue by Disapper** [BktechBrazil/Z2Z#2]
Fala pessoal, 

Usando o z2z recentemente dei por falta de algumas contas, que o script não fez, quando consegui identificar vi que os domínios dessas contas que não foram feito o export, estavam suspensas no painel de administração do zimbra.

sendo assim, só domínios ativos são exportados e qualquer outro status diferente disso não é exportado pelo script.

**Comment by fsschmidt** [comment]
Grato pelo report, iremos alterar a solução para considerar todos os domínios, mesmo os desativados.
