### ISSUE TITLE
Erros Export

### ISSUE THREAD

**Issue by julianodls** [BktechBrazil/Z2Z#3]
'OK: Executando como Zimbra.
'++++++++++++++++++++++++++++++++++++++++
Continuar (sim/nao)?sim
'Iniciando utilitario
'++++++++++++++++++++++++++++++++++++++++
'OK: comando ldapsearch existente.
'++++++++++++++++++++++++++++++++++++++++
'OK: comando zmmailbox existente.
'++++++++++++++++++++++++++++++++++++++++
'OK: comando zmshutil existente.
'++++++++++++++++++++++++++++++++++++++++
'OK: comando zmprov existente.
'++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++
'OK: Ambiente possui apenas um servidor Mailbox
'++++++++++++++++++++++++++++++++++++++++
'ERRO: O diretorio /root/Z2Z/export nao existe, abortando execucao

**Comment by fsschmidt** [comment]
- A solução deve ser executada em um diretório onde o zimbra possua permissão de escrita, neste caso foi executado no /root, portanto o usuário zimbra não poderá criar os arquivos.
